### ISSUE TITLE
廼和耑不是规范字

### ISSUE THREAD

**Issue by Lepton-Lee** [cdtym/digital-table-of-general-standard-chinese-characters#3]
《通用规范汉字表》8105字中没有廼和耑字。

![image](https://github.com/cdtym/digital-table-of-general-standard-chinese-characters/assets/95926073/d251e4a7-e106-48a7-be41-35ee98deea05)

**Comment by cdtym** [comment]
感谢指出！“廼(U+5EFC, 20_0_1)”应当更正为“迺(U+8FFA, 20_0_2)”，经查证这个问题只发生在README.txt中，表格本身没有问题，已更正。“耑(U+8011, 6837/83_1_1)”出现在《通用规范汉字表》P41，编号6837，三级字，所使用的文件见于http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201306/t20130601_186002.html，辛苦您再帮助核对一下。
![图片](https://github.com/user-attachments/assets/e4f7737d-0d6c-4758-a048-e09a23a62691)

**Comment by Lepton-Lee** [comment]
> 感谢指出！“廼(U+5EFC, 20_0_1)”应当更正为“迺(U+8FFA, 20_0_2)”，经查证这个问题只发生在README.txt中，表格本身没有问题，已更正。“耑(U+8011, 6837/83_1_1)”出现在《通用规范汉字表》P41，编号6837，三级字，所使用的文件见于[http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201306/t20130601_186002.html，辛苦您再帮助核对一下。](http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201306/t20130601_186002.html%EF%BC%8C%E8%BE%9B%E8%8B%A6%E6%82%A8%E5%86%8D%E5%B8%AE%E5%8A%A9%E6%A0%B8%E5%AF%B9%E4%B8%80%E4%B8%8B%E3%80%82) ![图片](https://private-user-images.githubusercontent.com/102949360/395824450-e4f7737d-0d6c-4758-a048-e09a23a62691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMjM2MTIsIm5iZiI6MTczNDIyMzMxMiwicGF0aCI6Ii8xMDI5NDkzNjAvMzk1ODI0NDUwLWU0Zjc3MzdkLTBkNmMtNDc1OC1hMDQ4LWUwOWEyM2E2MjY5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwMDQxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTZiMzc1YzU2MGZkODQ0ZGMzOGE4MDAwNTM5NjAyMjU4NmUyYjJiODdmOTllNTVlOGZhMDQwZTE4NTJkNGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zKin526HWPfieAwRCs7P1XWAXLwUmSDPz0dJKPwknf0)

是我看错了，“耑”确实是规范字。
